### ISSUE TITLE
Have an AbstractConfig type

### ISSUE THREAD

**Issue by disberd** [joshday/EasyConfig.jl#6]
Hello again!

I was thinking whether it would be possible or useful to create an AbstractConfig type where most of the AbstractDict interface functions are defined, and make just Config a default concrete subtype.

I don't know if it could have drawbacks, but it would allow to create a different more specific subtype (like PlotlyConfig) to solve the problem here https://github.com/JuliaComputing/PlotlyLight.jl/issues/12 by just defining a custom method for
`setproperty!(o::PlotlyConfig, k::Symbol, v)` to ensure that 2D arrays are stored as vectors of vectors.

I did not think into details about possible corner cases but I guess having the abstract type might give only potential benefits.

**Comment by joshday** [comment]
Another solution is to add a "processor" that defaults to `identity`,  e.g. `Config(; processor=identity)`.  Then PlotlyLight/whatever package can add their own processor function.

**Comment by joshday** [comment]
Actually never mind.  My suggestion breaks the constructor `Config(; kw...)`.  I'll think this through some more

**Comment by joshday** [comment]
Along with the closing of the PlotlyLight issue, I'm going to close this as well.
