### ISSUE TITLE
display of a config doesn't show keywords that are callable

### ISSUE THREAD

**Issue by vuthanho** [joshday/EasyConfig.jl#7]
Sorry about the weird title, I don't really know how to call this behavior as I'm not quite sure what's happening here.
```
julia> cfg = Config(x=0)
Config with 1 entry:
  :x => 0

julia> cfg.f()=begin
       return cfg.x+1
       end

julia> cfg
Config with 1 entry:
  :x => 0

julia> cfg.x #tab only shows x as a potential keyword

julia> cfg.f()
1

julia> cfg. #tab now shows f and x
f  x

julia> cfg.f #f is not a function
Config()

julia> cfg.f() #but it is still callable
1
```

**Comment by joshday** [comment]
I would have expected `cfg.f() = ...` to be an error.  My guess is that you want `cfg.f = () -> ...`

---

I'm not exactly sure how, but it seems that syntax defines a `(::Config)()` method:

```julia
julia> c = Config()
Config()

julia> c.f() = 1

julia> c()
1
```

Note that it hits `getproperty` rather than `setproperty!`.  If a key doesn't exist in a `Config`, an empty `Config()` is created (necessary for setting nested keys).  It must be some odd behavior related to that.  I can't quite parse the lowered code here.

```julia
julia> Meta.@lower c.f() = 1
:($(Expr(:thunk, CodeInfo(
    @ none within `top-level scope`
1 ─ %1 = Base.getproperty(c, :f)
│   %2 = Core.Typeof(%1)
│   %3 = Core.svec(%2)
│   %4 = Core.svec()
│   %5 = Core.svec(%3, %4, $(QuoteNode(:(#= REPL[10]:1 =#))))
│        $(Expr(:method, nothing, :(%5), CodeInfo(
    @ REPL[10]:1 within `none`
1 ─     return 1
)))
└──      return nothing
))))
```

**Comment by vuthanho** [comment]
Yes I wanted `cfg.f = () -> ...`, but I tried `cfg.f() = ...` out of curiosity and encountered this unexpected behavior.

Is it possible that `c.f() = 1` acts like `f() = 1` and doesn't throw an error because it doesn't know that `c.f` has been extended to an empty `Config()` ?
```
julia> c = Config()
Config()

julia> c.f()=1

julia> Config()()
1

julia> Config()() = 2
ERROR: syntax: invalid function name "Config()" around REPL[20]:1
Stacktrace:
 [1] top-level scope
   @ REPL[20]:1
```

**Comment by joshday** [comment]
Here's a MWE:

```Julia
struct Wrapper
    dict::Dict{Symbol, Any}
end

Base.getproperty(w::Wrapper, k::Symbol) = get!(getfield(w, :dict), k, Wrapper(Dict{Symbol,Any}()))

w = Wrapper(Dict(:x => 1))

w.f() = 1

w() == 1
```

**Comment by joshday** [comment]
I'm going to close this as the "problem" is in Base Julia.  There isn't a way to make this error from the EasyConfig side.
