### ISSUE TITLE
is it possible to embed javascript in Config()

### ISSUE THREAD

**Issue by asbisen** [joshday/EasyConfig.jl#9]
I have been playing around with [Apache ECharts](https://echarts.apache.org/en/index.html) and the JSON object it uses for plotting can take Javascript functions as callbacks. For example

```dict
{
type: "scatter",
symbol: "circle",
symbolSize: function (val) {return val[2] * 2; }
}
```

`Config()` object can take in string, but how do I render the callback functions in JSON without the quotes for string. Performing `JSON3.write()` gets me `"symbolSize: function (val) {return val[2] * 2; }"` but I would like to render `symbolSize: function (val) {return val[2] * 2; }`

**Comment by joshday** [comment]
I think you'd need to find/create a type that JSON3 will write as you want.
